name: Display CV In-Readme

on:
  push:
    branches: [ "main" ]

env:
  RESUME_FILE: resume.tex

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
            sudo apt-get update -y \

            # Install the full version of pdflatex and Pdftoppm 
            sudo apt-get install texlive-full poppler-utils -y 

    - name: Generate pdfs 
      run: |
        cat "${{ github.workspace }}/$RESUME_FILE"